POST http://localhost:9999/api/v1/product/
Content-Type: application/json

{
    "name":"starfruit",
    "type":"fruit"
}

###
POST http://localhost:9999/api/v1/users/
Content-Type: application/json

{
	"email":"scruffmcgruff@scruff.com",
    "firstName":"Scruff",
	"lastName":"McGruff",
    "password":"password123"
}

###
POST http://localhost:9999/api/v1/users/
Content-Type: application/json

{
	"email":"CPrentzler@scruff.com",
    "firstName":"Charisse",
	"lastName": "Prentzler",
    "password":"pass123"
}

###
POST http://localhost:9999/api/v1/users/
Content-Type: application/json

{
	"email":"testytest@test.com",
    "firstName":"Testy",
	"lastName": "McTest",
    "password":"pass123"
}