POST http://localhost:9999/api/v1/grocery-items/
Content-Type: application/json

{
    "name":"starfruit",
    "type":"fruit"
}

###
POST http://localhost:9999/api/users/
Content-Type: application/json

{
	"username":"scruffmcgruff",
    "name":"Scruff McGruff",
    "password":"password123"
}

###
POST http://localhost:9999/api/users/
Content-Type: application/json

{
	"username":"CPrentzler",
    "name":"Charisse Prentzler",
    "password":"pass123"
}

###
POST http://localhost:9999/api/users/
Content-Type: application/json

{
	"username":"testytest",
    "name":"Testy McTest",
    "password":"pass123"
}